version: '3.8'

services:

  mongodb:
    image: mongo:7
    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend

    container_name: backend

    depends_on:
      - mongodb

    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile

    container_name: nginx-web

    depends_on:
      - backend

    ports:
      - "8081:81"

volumes:
  mongo-data: